export const images = {
  logo: '/images/logo.webp',
  mobileMenuLogo: '/images/mobile-menu-logo.webp',
  footerLogo: '/images/footer-logo.webp',
  hero: '/images/hero.webp',
  gallery: [
    '/images/gallery-1.webp',
    '/images/gallery-2.webp',
    '/images/gallery-3.webp',
    '/images/gallery-4.webp',
  ],
  featureHouse: '/images/feature-house.webp',
  whyChoose: '/images/why-choose.webp',
  ctaBg: '/images/cta-bg.webp',
  testimonialAvatar: '/images/testimonial-avatar.webp',
  services: [
    '/images/service-1.webp',
    '/images/service-2.webp',
    '/images/service-3.webp',
    '/images/service-4.webp',
    '/images/service-5.webp',
    '/images/service-6.webp',
    '/images/service-7.webp',
    '/images/service-8.webp',
    '/images/service-9.webp',
  ],
  servicesPage: {
    hero: '/images/services-hero.webp',
    heroMobile: '/images/services-hero-mobile.webp',
    cta: '/images/services-cta.webp',
    howItWorks: [
      '/images/services/how-it-works-1.webp',
      '/images/services/how-it-works-2.webp',
      '/images/services/how-it-works-3.webp',
      '/images/services/how-it-works-4.webp',
    ],
  },
  contactPage: {
    hero: '/images/contact-hero-alt.webp',
  },
  aboutPage: {
    hero: '/images/about/hero.webp',
    whoWeAre: {
      back: '/images/about/who-we-are-2.webp',
      front: '/images/about/who-we-are-1.webp',
    },
    values: '/images/about/values.webp',
    experience: ['/images/about/experience-1.webp', '/images/about/experience-2.webp'],
    cta: '/images/cta-bg.webp',
    ctaMobile: '/images/about/cta-mobile.webp',
  },
  projectsPage: {
    hero: '/images/projects/hero.webp',
    heroMobile: '/images/projects/hero-mobile.webp',
    items: [
      '/images/projects/project-1.webp',
      '/images/projects/project-2.webp',
      '/images/projects/project-3.webp',
      '/images/projects/project-4.webp',
      '/images/projects/project-5.webp',
      '/images/projects/project-6.webp',
    ],
  },
} as const
